# -*- coding: utf-8 -*-


futurize_fixes = {
    'libfuturize.fixes.fix_metaclass',
    'lib2to3.fixes.fix_dict',
}

pasteurize_fixes = {
    'libpasteurize.fixes.fix_metaclass',
    'lib2to3.fixes.fix_dict',
}

all_libfutuize_fixes = {
    'libfuturize.fixes.fix_absolute_import',
    'libfuturize.fixes.fix_add__future__imports_except_unicode_literals',
    'libfuturize.fixes.fix_basestring',
    'libfuturize.fixes.fix_bytes',
    'libfuturize.fixes.fix_cmp',
    'libfuturize.fixes.fix_division',
    'libfuturize.fixes.fix_division_safe',
    'libfuturize.fixes.fix_execfile',
    'libfuturize.fixes.fix_future_builtins',
    'libfuturize.fixes.fix_future_standard_library',
    'libfuturize.fixes.fix_future_standard_library_urllib',
    'libfuturize.fixes.fix_metaclass',
    'libfuturize.fixes.fix_next_call',
    'libfuturize.fixes.fix_object',
    'libfuturize.fixes.fix_oldstr_wrap',
    'libfuturize.fixes.fix_order___future__imports',
    'libfuturize.fixes.fix_print',
    'libfuturize.fixes.fix_print_with_import',
    'libfuturize.fixes.fix_raise',
    # 'libfuturize.fixes.fix_remove_old__future__imports',
    'libfuturize.fixes.fix_unicode_keep_u',
    'libfuturize.fixes.fix_unicode_literals_import',
    'libfuturize.fixes.fix_UserDict',
    'libfuturize.fixes.fix_xrange_with_import',
}

all_libpasteurize_fixes = {
    'libpasteurize.fixes.fix_add_all_future_builtins',
    'libpasteurize.fixes.fix_add_all__future__imports',
    'libpasteurize.fixes.fix_add_future_standard_library_import',
    'libpasteurize.fixes.fix_annotations',
    'libpasteurize.fixes.fix_division',
    'libpasteurize.fixes.fix_features',
    'libpasteurize.fixes.fix_fullargspec',
    'libpasteurize.fixes.fix_future_builtins',
    'libpasteurize.fixes.fix_getcwd',
    'libpasteurize.fixes.fix_imports2',
    'libpasteurize.fixes.fix_imports',
    'libpasteurize.fixes.fix_kwargs',
    'libpasteurize.fixes.fix_memoryview',
    'libpasteurize.fixes.fix_metaclass',
    'libpasteurize.fixes.fix_newstyle',
    'libpasteurize.fixes.fix_next',
    'libpasteurize.fixes.fix_printfunction',
    'libpasteurize.fixes.fix_raise_',
    'libpasteurize.fixes.fix_raise',
    'libpasteurize.fixes.fix_throw',
    'libpasteurize.fixes.fix_unpacking',
}

lib2to3_fixes = {
    'lib2to3.fixes.fix_apply',
    'lib2to3.fixes.fix_asserts',
    'lib2to3.fixes.fix_basestring',
    'lib2to3.fixes.fix_buffer',
    'lib2to3.fixes.fix_dict',
    'lib2to3.fixes.fix_except',
    'lib2to3.fixes.fix_execfile',
    'lib2to3.fixes.fix_exec',
    'lib2to3.fixes.fix_exitfunc',
    'lib2to3.fixes.fix_filter',
    'lib2to3.fixes.fix_funcattrs',
    'lib2to3.fixes.fix_future',
    'lib2to3.fixes.fix_getcwdu',
    'lib2to3.fixes.fix_has_key',
    'lib2to3.fixes.fix_idioms',
    'lib2to3.fixes.fix_import',
    'lib2to3.fixes.fix_imports2',
    'lib2to3.fixes.fix_imports',
    'lib2to3.fixes.fix_input',
    'lib2to3.fixes.fix_intern',
    'lib2to3.fixes.fix_isinstance',
    'lib2to3.fixes.fix_itertools_imports',
    'lib2to3.fixes.fix_itertools',
    'lib2to3.fixes.fix_long',
    'lib2to3.fixes.fix_map',
    'lib2to3.fixes.fix_metaclass',
    'lib2to3.fixes.fix_methodattrs',
    'lib2to3.fixes.fix_ne',
    'lib2to3.fixes.fix_next',
    'lib2to3.fixes.fix_nonzero',
    'lib2to3.fixes.fix_numliterals',
    'lib2to3.fixes.fix_operator',
    'lib2to3.fixes.fix_paren',
    'lib2to3.fixes.fix_print',
    'lib2to3.fixes.fix_raise',
    'lib2to3.fixes.fix_raw_input',
    'lib2to3.fixes.fix_reduce',
    'lib2to3.fixes.fix_renames',
    'lib2to3.fixes.fix_repr',
    'lib2to3.fixes.fix_set_literal',
    'lib2to3.fixes.fix_standarderror',
    'lib2to3.fixes.fix_sys_exc',
    'lib2to3.fixes.fix_throw',
    'lib2to3.fixes.fix_tuple_params',
    'lib2to3.fixes.fix_types',
    'lib2to3.fixes.fix_unicode',
    'lib2to3.fixes.fix_urllib',
    'lib2to3.fixes.fix_ws_comma',
    'lib2to3.fixes.fix_xrange',
    'lib2to3.fixes.fix_xreadlines',
    'lib2to3.fixes.fix_zip',
}
