name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python:
          - [2, 7]
          - [3, 6]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python[0] }}.${{ matrix.python[1] }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python[0] }}.${{ matrix.python[1] }}
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Test with tox
      run: |
        tox -e py${{ matrix.python[0] }}${{ matrix.python[1] }}
        
